INSERT INTO t_pad_usb (id, version) VALUES
  (1, '1.0.0'),
  (2, '2.1.1'),
  (3, '3.2.1');

INSERT INTO t_pad_sound_card (id, version, usb_id) VALUES
  (1, '1.0.0', 1),
  (2, 'A_2.1.1', 2),
  (3, '3.2.1', 3);

INSERT INTO t_pad_os (id, created_at, end_date, name, version) VALUES
  (1, CURRENT_TIMESTAMP, NULL, 'Ubuntu','20.04_lts'),
  (2, CURRENT_TIMESTAMP, NULL, 'Debian','10_lts'),
  (3, CURRENT_TIMESTAMP, NULL, 'ArchLinux','5.4.69-1_lts'),
  (4, CURRENT_TIMESTAMP, NULL, 'Manjaro','18.1.0_lts'),
  (5, CURRENT_TIMESTAMP, NULL, 'Red Hat Enterprise Linux-RHEL','7'),
  (6, CURRENT_TIMESTAMP, NULL, 'CentOS','8.0'),
  (7, CURRENT_TIMESTAMP, NULL, 'Windows','10'),
  (8, CURRENT_TIMESTAMP, NULL, 'Windows Server','2019'),
  (9, CURRENT_TIMESTAMP, NULL, 'Android','11');


INSERT INTO t_pad_computer (id, state, state_date_time, computer_type, created_at, os_id, sound_card_id) VALUES
  (1, 'ACTIVE', CURRENT_TIMESTAMP, 'PERSONAL_COMPUTER', CURRENT_TIMESTAMP, 1, 1),
  (2, 'INACTIVE', CURRENT_TIMESTAMP, 'AI_SUPER_PC', CURRENT_TIMESTAMP, 2, NULL),
  (3, 'DELETED', CURRENT_TIMESTAMP, 'TABLET', CURRENT_TIMESTAMP, 9, 2),
  (4, 'ACTIVE', CURRENT_TIMESTAMP, 'SERVER', CURRENT_TIMESTAMP, 5, NULL),
  (5, 'INACTIVE', CURRENT_TIMESTAMP, 'WORKSTATION', CURRENT_TIMESTAMP, NULL, NULL),
  (6, 'ACTIVE', CURRENT_TIMESTAMP, 'PERSONAL_COMPUTER', CURRENT_TIMESTAMP, 1, 3),
  (7, 'ACTIVE', CURRENT_TIMESTAMP, 'PERSONAL_COMPUTER', CURRENT_TIMESTAMP, 7, 1),
  (8, 'ACTIVE', CURRENT_TIMESTAMP, 'SERVER', CURRENT_TIMESTAMP, 6, NULL),
  (9, 'ACTIVE', CURRENT_TIMESTAMP, 'SERVER', CURRENT_TIMESTAMP, 3, NULL),
  (10, 'ACTIVE', CURRENT_TIMESTAMP, 'CELLULAR', CURRENT_TIMESTAMP, 9, 2),
  (11, 'INACTIVE', CURRENT_TIMESTAMP, 'CELLULAR', CURRENT_TIMESTAMP, 9, 2);

